version: '3'

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile for your Go app
    volumes:
      - .:/go/src/github.com/username/goapp
    platform: linux/amd64
    ports:
      - "8080:8080"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
